name: Testing pick_a_pylint

on: [push]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Versions
      run: |
        python3 --version
    - name: ping the archive
      continue-on-error: true
      run: |
        ping -R -c 3 azure.archive.ubuntu.com
    - name: curl the archive
      continue-on-error: true
      run: |
        curl http://azure.archive.ubuntu.com/ubuntu/ -w "status: %{http_code}\nnum_redirects: %{num_redirects}\ntime_connect: %{time_connect}\n"
    - name: apt update
      run: |
        sudo apt-get update
