name: Testing pick_a_pylint

on: [push]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: sommersoft/actions-ci-circuitpython-libs
        ref: pick_a_pylint
        path: actions-ci
    - name: Install deps
      run: |
        source actions-ci/install.sh
