name: Schedule testing

on:
  push:
    branches:
      - schedule
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startswith(github.repository, 'adafruit')
    steps:
      - name: Echo repo name
        run: echo ${{ github.repository }}
      - name: Echo something else
        run: echo 'something else'
