name: Schedule testing

on:
  push:
    branches:
      - schedule
  schedule:
    - cron: '1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'sommersoft/actions_testing'
    steps:
      - name: Echo repo name
        run: echo ${{ github.repository }}
