name: Schedule testing

on:
  push
  schedule:
    - cron: 5 * * * *
      if: github.repository == 'sommersoft/actions_testing'

jobs:
  steps:
    - name: Echo repo name
      run: echo {{ github.repository }}
